### ISSUE TITLE
Add functionality for determining toppings

### ISSUE THREAD

**Issue by mynar7** [ialex/how-many-pizza#6]
Currently the App does not take into account the different topping combinations. For example, if I have x number of vegetarian pizza-eaters at my party, how many veggie pizzas should I order?

Also, it might be helpful to have topping recommendations for pizzas. Eg. 50% pepperoni pizzas, 50% cheese pizzas.

**Comment by ialex** [comment]
You can run it two times one for meat eater and another for vegetarians. Toppings vary for each pizza place it will not be covered in the API.
